"""Nginx config file operations with syntax checks and rollback."""

from __future__ import annotations

import os
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path

from loguru import logger

from nam.config import ensure_runtime_dirs
from nam.models import AppConfig, ManagerConfig, OperationResult
from nam.services.backup_service import BackupService
from nam.services.template_service import TemplateService
from nam.utils.paths import can_write_path, unlink_if_exists
from nam.utils.shell import command_exists, run_command
from nam.utils.validators import safe_domain_filename

MANAGED_MARKER = "managed_by: nginx-app-manager"


@dataclass
class PathSnapshot:
    """Minimal snapshot of a file or symlink for rollback."""

    path: Path
    existed: bool
    was_symlink: bool = False
    symlink_target: str | None = None
    content: bytes | None = None
    mode: int | None = None

    @classmethod
    def capture(cls, path: Path) -> PathSnapshot:
        """Capture a path before mutation."""
        if path.is_symlink():
            return cls(
                path=path,
                existed=True,
                was_symlink=True,
                symlink_target=str(path.readlink()),
            )
        if path.exists():
            return cls(
                path=path,
                existed=True,
                content=path.read_bytes(),
                mode=stat.S_IMODE(path.stat().st_mode),
            )
        return cls(path=path, existed=False)

    def restore(self) -> None:
        """Restore this snapshot."""
        unlink_if_exists(self.path)
        if not self.existed:
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if self.was_symlink:
            if self.symlink_target is None:
                return
            self.path.symlink_to(self.symlink_target)
            return
        if self.content is None:
            return
        self.path.write_bytes(self.content)
        if self.mode is not None:
            os.chmod(self.path, self.mode)


class NginxService:
    """Manage generated Nginx server block files safely."""

    def __init__(
        self,
        config: ManagerConfig,
        *,
        template_service: TemplateService | None = None,
        backup_service: BackupService | None = None,
    ) -> None:
        self.config = config
        self.template_service = template_service or TemplateService()
        self.backup_service = backup_service or BackupService(config)

    def available_path(self, domain: str) -> Path:
        """Return the sites-available path for a domain."""
        return self.config.nginx.sites_available / safe_domain_filename(domain)

    def enabled_path(self, domain: str) -> Path:
        """Return the sites-enabled path for a domain."""
        return self.config.nginx.sites_enabled / safe_domain_filename(domain)

    def render(self, app: AppConfig) -> str:
        """Render a server block."""
        return self.template_service.render_server_block(app, self.config)

    def is_managed_config(self, path: Path) -> bool:
        """Return true when a file appears to be generated by this tool."""
        if not path.exists() or path.is_symlink():
            return False
        try:
            head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:12])
        except UnicodeDecodeError:
            return False
        return MANAGED_MARKER in head

    def permission_error(self, paths: list[Path]) -> OperationResult | None:
        """Return a friendly write-permission error for production writes."""
        if self.config.mode == "development":
            return None
        blocked = [str(path) for path in paths if not can_write_path(path)]
        if not blocked:
            return None
        return OperationResult(
            ok=False,
            message="Write permission required. Re-run this command with sudo.",
            details={"paths": blocked},
        )

    def ensure_directories(self, *, create: bool = False) -> OperationResult:
        """Check or create runtime directories."""
        paths = [
            self.config.data_dir,
            self.config.backup_dir,
            self.config.log_dir,
            self.config.apps_file.parent,
            self.config.nginx.sites_available,
            self.config.nginx.sites_enabled,
        ]
        missing = [str(path) for path in paths if not path.exists()]
        if missing and not create:
            return OperationResult(
                ok=False,
                message="Required directories are missing.",
                details={"missing": missing},
            )
        if create:
            ensure_runtime_dirs(self.config, include_nginx_dirs=True)
            if self.config.mode == "development" and not self.config.nginx.nginx_conf.exists():
                self.config.nginx.nginx_conf.write_text(
                    "events {}\nhttp { include sites-enabled/*.conf; }\n",
                    encoding="utf-8",
                )
        return OperationResult(
            ok=True,
            message="Directories are ready.",
            details={"paths": [str(path) for path in paths]},
        )

    def version(self) -> OperationResult:
        """Return the installed Nginx version."""
        result = run_command([self.config.nginx.nginx_bin, "-v"])
        return OperationResult(
            ok=result.ok,
            message=result.combined_output or "nginx version check completed.",
            details={"returncode": result.returncode},
        )

    def test_config(self) -> OperationResult:
        """Run or simulate ``nginx -t``."""
        if self.config.mode == "development":
            return OperationResult(ok=True, message="Development mode: simulated nginx -t passed.")
        result = run_command(
            [self.config.nginx.nginx_bin, "-t", "-c", self.config.nginx.nginx_conf],
            timeout=30,
        )
        return OperationResult(
            ok=result.ok,
            message=result.combined_output or "nginx -t completed.",
            details={"returncode": result.returncode},
        )

    def reload(self) -> OperationResult:
        """Reload Nginx through systemd, falling back to ``nginx -s reload``."""
        if self.config.mode == "development":
            return OperationResult(
                ok=True,
                message="Development mode: simulated nginx reload passed.",
            )
        if command_exists(self.config.nginx.systemctl_bin):
            result = run_command(
                [self.config.nginx.systemctl_bin, "reload", self.config.nginx.service_name],
                timeout=30,
            )
        else:
            result = run_command([self.config.nginx.nginx_bin, "-s", "reload"], timeout=30)
        return OperationResult(
            ok=result.ok,
            message=result.combined_output or "nginx reload completed.",
            details={"returncode": result.returncode},
        )

    def write_server_block(
        self,
        app: AppConfig,
        *,
        enable: bool,
        dry_run: bool = False,
        force: bool = False,
    ) -> OperationResult:
        """Safely write, optionally enable, test, reload, and roll back on failure."""
        rendered = self.render(app)
        available = self.available_path(app.domain)
        enabled = self.enabled_path(app.domain)
        details: dict[str, object] = {
            "available_path": str(available),
            "enabled_path": str(enabled),
            "rendered_config": rendered,
        }

        if dry_run:
            return OperationResult(
                ok=True,
                message="Dry run: no files were changed.",
                details=details,
            )

        permission_error = self.permission_error([available, enabled, self.config.backup_dir])
        if permission_error is not None:
            return permission_error

        self.ensure_directories(create=True)
        if available.exists() and not self.is_managed_config(available) and not force:
            return OperationResult(
                ok=False,
                message=f"Refusing to overwrite unmanaged config: {available}",
                details=details,
            )
        if enabled.exists() and not enabled.is_symlink() and not force:
            return OperationResult(
                ok=False,
                message=f"Refusing to replace non-symlink enabled config: {enabled}",
                details=details,
            )

        available_snapshot = PathSnapshot.capture(available)
        enabled_snapshot = PathSnapshot.capture(enabled)
        backup = self.backup_service.backup_file(available, reason="pre-write")
        if backup is not None:
            details["backup_path"] = str(backup.backup_path)

        tmp_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                dir=available.parent,
                prefix=f".{available.name}.",
                delete=False,
            ) as tmp_file:
                tmp_file.write(rendered)
                tmp_file.write("\n")
                tmp_path = Path(tmp_file.name)
            os.replace(tmp_path, available)
            os.chmod(available, 0o644)
            tmp_path = None

            if enable:
                unlink_if_exists(enabled)
                enabled.symlink_to(available)
            else:
                unlink_if_exists(enabled)

            test_result = self.test_config()
            details["nginx_test"] = test_result.model_dump(mode="json")
            if not test_result.ok:
                available_snapshot.restore()
                enabled_snapshot.restore()
                logger.error("nginx -t failed; rolled back {}", available)
                return OperationResult(
                    ok=False,
                    message=f"nginx -t failed; rolled back changes. {test_result.message}",
                    details=details,
                )

            reload_result = self.reload()
            details["nginx_reload"] = reload_result.model_dump(mode="json")
            if not reload_result.ok:
                available_snapshot.restore()
                enabled_snapshot.restore()
                self.reload()
                logger.error("nginx reload failed; rolled back {}", available)
                return OperationResult(
                    ok=False,
                    message=f"nginx reload failed; rolled back changes. {reload_result.message}",
                    details=details,
                )

            logger.info("Wrote Nginx config for {} (enabled={})", app.domain, enable)
            return OperationResult(ok=True, message="Nginx configuration applied.", details=details)
        except OSError as exc:
            if tmp_path is not None:
                unlink_if_exists(tmp_path)
            available_snapshot.restore()
            enabled_snapshot.restore()
            logger.exception("Failed to write config for {}", app.domain)
            return OperationResult(
                ok=False,
                message=f"Failed to write config; rolled back: {exc}",
                details=details,
            )

    def disable(self, domain: str, *, dry_run: bool = False) -> OperationResult:
        """Disable a managed config by removing its sites-enabled symlink."""
        enabled = self.enabled_path(domain)
        details: dict[str, object] = {"enabled_path": str(enabled)}
        if dry_run:
            return OperationResult(
                ok=True,
                message="Dry run: no files were changed.",
                details=details,
            )
        permission_error = self.permission_error([enabled])
        if permission_error is not None:
            return permission_error
        snapshot = PathSnapshot.capture(enabled)
        try:
            unlink_if_exists(enabled)
            test_result = self.test_config()
            details["nginx_test"] = test_result.model_dump(mode="json")
            if not test_result.ok:
                snapshot.restore()
                return OperationResult(
                    ok=False,
                    message=f"nginx -t failed after disable; restored link. {test_result.message}",
                    details=details,
                )
            reload_result = self.reload()
            details["nginx_reload"] = reload_result.model_dump(mode="json")
            if not reload_result.ok:
                snapshot.restore()
                self.reload()
                return OperationResult(
                    ok=False,
                    message=(
                        "nginx reload failed after disable; restored link. "
                        f"{reload_result.message}"
                    ),
                    details=details,
                )
            logger.info("Disabled Nginx config for {}", domain)
            return OperationResult(
                ok=True,
                message="Nginx configuration disabled.",
                details=details,
            )
        except OSError as exc:
            snapshot.restore()
            return OperationResult(
                ok=False,
                message=f"Failed to disable config; restored link: {exc}",
                details=details,
            )

    def remove_available(self, domain: str, *, dry_run: bool = False) -> OperationResult:
        """Remove the managed sites-available file after backing it up."""
        available = self.available_path(domain)
        details: dict[str, object] = {"available_path": str(available)}
        if dry_run:
            return OperationResult(
                ok=True,
                message="Dry run: no files were changed.",
                details=details,
            )
        permission_error = self.permission_error([available, self.config.backup_dir])
        if permission_error is not None:
            return permission_error
        if not available.exists():
            return OperationResult(
                ok=True,
                message="Config file already absent.",
                details=details,
            )
        if not self.is_managed_config(available):
            return OperationResult(
                ok=False,
                message=f"Refusing to delete unmanaged config: {available}",
                details=details,
            )
        backup = self.backup_service.backup_file(available, reason="pre-delete")
        if backup is not None:
            details["backup_path"] = str(backup.backup_path)
        available.unlink()
        logger.info("Removed Nginx config file {}", available)
        return OperationResult(ok=True, message="Config file removed.", details=details)
